name: Build ShielD7L
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permiso a Gradle
        run: chmod +x gradlew

      - name: Compilar APK
        run: ./gradlew clean assembleDebug --no-daemon

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: ShielD7L-APK
          path: app/build/outputs/apk/debug/*.apk
